export type EmotionType = "feliz" | "triste" | "enojado" | "ansioso" | "motivado";

export const EMOTIONS: Record<EmotionType, string[]> = {
  feliz: [
    "La felicidad está en los pequeños momentos.",
    "Sonríe, hoy es un buen día.",
    "Tu energía ilumina todo a tu alrededor.",
    "La alegría es tu mejor accesorio.",
    "Sigue brillando, el mundo lo nota.",
    "Hoy es un día para sentirte libre.",
    "Lo bueno llega para quien vibra bonito.",
    "Tu risa vale más que mil palabras.",
    "Estás donde necesitas estar.",
    "Celebra tu paz.",
    "Hoy todo fluye para ti.",
    "Tu luz inspira a otros.",
    "La vida se ve mejor con tu sonrisa.",
    "Tu felicidad contagia.",
    "Todo lo bueno te encuentra.",
    "Tú eres tu mejor versión.",
    "La alegría te queda bien.",
    "Hoy respiras gratitud.",
    "Tu vibra es magia pura.",
    "Eres un rayo de sol para el mundo.",
  ],
  triste: [
    "Está bien no estar bien.",
    "Respira, esto también pasará.",
    "No estás solo.",
    "Eres más fuerte de lo que crees.",
    "Llorar también es sanar.",
    "Un día a la vez.",
    "No te rindas, esto es temporal.",
    "Todo mejora.",
    "Tu corazón merece paz.",
    "Tienes permiso de sentir.",
    "Lo estás haciendo bien.",
    "Aunque duela, estás creciendo.",
    "Este no es tu final.",
    "Eres importante.",
    "Cada día trae una esperanza nueva.",
    "No te castigues por sentir.",
    "Tu valor no cambia.",
    "La vida aún tiene cosas hermosas para ti.",
    "Sé amable contigo.",
    "Tu tristeza no te define.",
  ],
  enojado: [
    "Respira antes de reaccionar.",
    "La calma siempre vuelve.",
    "No todo merece tu energía.",
    "Eres más que este momento.",
    "Tranquilo, todo se acomoda.",
    "No pierdas tu paz.",
    "Piensa antes de hablar.",
    "El control está en ti.",
    "Respira profundo.",
    "Esto no durará para siempre.",
    "Puedes manejarlo.",
    "No te dejes consumir.",
    "Eres más grande que tu enojo.",
    "Despeja tu mente.",
    "La serenidad es tu aliada.",
    "Toma distancia si lo necesitas.",
    "Tú decides cómo responder.",
    "Tu paz vale más.",
    "Calma, todo estará bien.",
    "Respira, suéltalo, sigue.",
  ],
  ansioso: [
    "No tienes que tener todo resuelto hoy.",
    "Respira, estás a salvo.",
    "Tu mente es fuerte.",
    "Nada malo está pasando ahora.",
    "Concéntrate en este momento.",
    "Eres más valiente de lo que crees.",
    "Todo estará bien.",
    "Un paso a la vez.",
    "Estás haciendo lo mejor que puedes.",
    "Tu respiración te guía.",
    "No estás atrasado.",
    "Confía en ti.",
    "No eres tus pensamientos.",
    "Eres más que tu ansiedad.",
    "Suelta lo que no controlas.",
    "Eres suficiente.",
    "Vas a superarlo.",
    "La calma regresa, siempre.",
    "Tienes fuerza para seguir.",
    "Esto no te controla.",
  ],
  motivado: [
    "Hoy es tu día.",
    "Tú puedes con todo.",
    "No te detengas.",
    "Cada paso cuenta.",
    "Vas por buen camino.",
    "Eres imparable.",
    "Tu esfuerzo dará frutos.",
    "Hazlo por ti.",
    "Sigue luchando.",
    "Enfócate y avanza.",
    "Nada es imposible.",
    "Confía en tu proceso.",
    "Lo lograrás.",
    "Tienes todo lo necesario.",
    "Sigue creyendo en ti.",
    "Tu disciplina te llevará lejos.",
    "El éxito te espera.",
    "Hazlo aunque tengas miedo.",
    "No pares ahora.",
    "Estás más cerca de lo que crees.",
  ],
};
