export type EmotionType = "feliz" | "triste" | "enojado" | "ansioso" | "motivado";

export const EMOTIONS: Record<EmotionType, string[]> = {
  feliz: [
    "La felicidad no es un destino, es el camino.",
    "Hoy es un buen día para sonreír.",
    "Lo que haces con alegría, vuelve multiplicado.",
    "La vida es mejor cuando sonríes.",
    "El optimismo abre puertas donde otros ven muros.",
    "Cada momento feliz es un tesoro.",
    "Sonríe, es contagioso.",
    "La felicidad está en las pequeñas cosas.",
    "Sigue tu corazón y serás feliz.",
    "Lo bueno de hoy será tu recuerdo feliz mañana.",
    "Ríe, sueña y disfruta.",
    "La alegría multiplica la vida.",
    "El día es tan brillante como tu actitud.",
    "Cree en lo positivo.",
    "Pequeños momentos, grandes sonrisas.",
    "El buen humor abre puertas.",
    "Vive hoy con alegría.",
    "La felicidad se comparte.",
    "Cultiva gratitud y alegría.",
    "Haz que tu sonrisa cuente."
  ],
  triste: [
    "Está bien sentirse mal, pero no te quedes ahí.",
    "Lágrimas hoy, fuerza mañana.",
    "Incluso las noches más oscuras terminan con un amanecer.",
    "El dolor también enseña lecciones.",
    "Respira y toma un momento para ti.",
    "Las emociones fluyen, déjalas pasar.",
    "Después de la tormenta, llega la calma.",
    "Permítete sentir sin juzgarte.",
    "Cada tristeza tiene un aprendizaje.",
    "La tristeza es parte de ser humano.",
    "Busca un pequeño momento de alegría hoy.",
    "A veces llorar es sanar.",
    "Los días difíciles también pasan.",
    "No estás solo en tus emociones.",
    "Acepta tus sentimientos como son.",
    "El tiempo ayuda a aliviar la pena.",
    "El duelo y la tristeza son normales.",
    "Cuidarte a ti mismo es prioridad.",
    "Habla de lo que sientes.",
    "Después de la tristeza, la luz vuelve."
  ],
  enojado: [
    "Respira. No todo merece tu energía.",
    "Tu paz vale más que cualquier discusión.",
    "No dejes que un mal momento arruine tu día.",
    "Cuenta hasta diez antes de reaccionar.",
    "La paciencia es un superpoder.",
    "Canaliza tu energía de manera positiva.",
    "Respira profundo y suelta la tensión.",
    "La calma es más fuerte que la ira.",
    "No pelees contra lo que no puedes controlar.",
    "Transforma tu enojo en acción constructiva.",
    "El autocontrol te da poder.",
    "No guardes rencor.",
    "Hablar con calma siempre ayuda.",
    "Aprende a soltar lo que te molesta.",
    "Tu bienestar vale más que un conflicto.",
    "La ira es momentánea, la paz es duradera.",
    "El silencio puede ser más sabio que gritar.",
    "Respira y reflexiona antes de actuar.",
    "Haz ejercicio para liberar tensión.",
    "Recuerda que la ira no define quién eres."
  ],
  ansioso: [
    "Un paso a la vez, vas bien.",
    "Respira profundo, lo estás haciendo mejor de lo que crees.",
    "No tienes que tener todo resuelto hoy.",
    "Confía en que lo harás bien.",
    "El presente es suficiente.",
    "Concéntrate en lo que puedes controlar.",
    "Un minuto de calma cambia todo.",
    "No dejes que la mente te abrume.",
    "Tu ansiedad no define tu capacidad.",
    "Tómate un respiro y sigue adelante.",
    "Pequeños logros son grandes victorias.",
    "Cada día es una nueva oportunidad.",
    "Haz una cosa a la vez.",
    "Deja ir lo que no puedes cambiar.",
    "Respira y visualiza lo positivo.",
    "Tu esfuerzo es suficiente.",
    "La ansiedad es pasajera, tu fuerza es permanente.",
    "Busca momentos de tranquilidad hoy.",
    "Cree en tu proceso.",
    "Confía en ti mismo."
  ],
  motivado: [
    "Cree en ti, eres capaz de mucho más.",
    "Si el plan no funciona, cambia el plan, no la meta.",
    "Hazlo por la persona en la que te quieres convertir.",
    "Cada paso te acerca a tu sueño.",
    "La disciplina crea resultados.",
    "Tu esfuerzo vale más que cualquier excusa.",
    "Sigue adelante, incluso cuando duela.",
    "La motivación viene de la acción.",
    "No esperes, crea tu oportunidad.",
    "Lo que hoy siembres, mañana cosecharás.",
    "Confía en tu potencial.",
    "Persiste y lograrás tus metas.",
    "El éxito es la suma de pequeños esfuerzos.",
    "No te rindas ante el primer obstáculo.",
    "Mantén tu enfoque y claridad.",
    "El trabajo duro supera la suerte.",
    "Motívate a ti mismo cada día.",
    "Cree que puedes y ya estás a mitad de camino.",
    "El progreso es mejor que la perfección.",
    "Cada día es una nueva oportunidad para brillar."
  ],
};

export const EMOTION_COLORS: Record<EmotionType, string> = {
  feliz: "#FFD700",
  triste: "#1E90FF",
  enojado: "#FF4500",
  ansioso: "#8A2BE2",
  motivado: "#32CD32",
};
